packages:
  - packages/*

catalog:
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/user-event': ^14.6.1
  '@vitest/browser': ^4.0.18
  eslint: ^9.39.4
  eslint-config-ts-prefixer: ^4.1.6
  globals: ^17.4.0
  happy-dom: ^20.8.3
  playwright: ^1.58.2
  typescript: ^5.9.3
  typescript-eslint: ^8.57.0
  vitest: ^4.0.18
  zod: 4.3.6

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - prisma
  - sharp
  - unrs-resolver
