import { describe, it, expect } from 'vitest'
import { render } from '@testing-library/react'
import RootLayout, { metadata } from '../app/layout'

// Mock Next.js fonts
vi.mock('next/font/google', () => ({
  Geist: vi.fn(() => ({
    variable: '--font-geist-sans',
  })),
  Geist_Mono: vi.fn(() => ({
    variable: '--font-geist-mono',
  })),
}))

describe('RootLayout', () => {
  it('should render children correctly', () => {
    const { getByText } = render(
      <RootLayout>
        <div>Test Content</div>
      </RootLayout>
    )

    expect(getByText('Test Content')).toBeInTheDocument()
  })

  it('should render component structure correctly', () => {
    const { container } = render(
      <RootLayout>
        <div>Content</div>
      </RootLayout>
    )

    // In unit tests, we can't test the actual HTML/body structure
    // but we can verify the component renders without errors
    expect(container.firstChild).toBeInTheDocument()
  })

  it('should have correct font configuration', () => {
    // We can't test actual CSS class application in unit tests,
    // but we can verify the font configuration is imported
    // This test verifies the component doesn't throw errors with font setup
    expect(() => {
      render(
        <RootLayout>
          <div>Content with fonts</div>
        </RootLayout>
      )
    }).not.toThrow()
  })

  it('should have correct metadata export', () => {
    expect(metadata).toEqual({
      title: 'Create Next App',
      description: 'Generated by create next app',
    })
  })

  it('should handle multiple children', () => {
    const { getByText } = render(
      <RootLayout>
        <div>First Child</div>
        <div>Second Child</div>
      </RootLayout>
    )

    expect(getByText('First Child')).toBeInTheDocument()
    expect(getByText('Second Child')).toBeInTheDocument()
  })

  it('should render child components correctly', () => {
    const { getByRole } = render(
      <RootLayout>
        <main>Main Content</main>
      </RootLayout>
    )

    // We can test that child components are rendered correctly
    const main = getByRole('main')
    expect(main).toBeInTheDocument()
    expect(main).toHaveTextContent('Main Content')
  })

  it('should accept readonly children prop', () => {
    // This test ensures TypeScript types are working correctly
    const children: Readonly<{ children: React.ReactNode }> = {
      children: <div>Readonly Children</div>
    }

    const { getByText } = render(
      <RootLayout {...children}>
      </RootLayout>
    )

    expect(getByText('Readonly Children')).toBeInTheDocument()
  })

  it('should handle React fragments as children', () => {
    const { getByText } = render(
      <RootLayout>
        <>
          <div>Fragment Child 1</div>
          <div>Fragment Child 2</div>
        </>
      </RootLayout>
    )

    expect(getByText('Fragment Child 1')).toBeInTheDocument()
    expect(getByText('Fragment Child 2')).toBeInTheDocument()
  })

  it('should handle null children gracefully', () => {
    expect(() => {
      render(
        <RootLayout>
          {null}
        </RootLayout>
      )
    }).not.toThrow()
  })

  it('should handle undefined children gracefully', () => {
    expect(() => {
      render(
        <RootLayout>
          {undefined}
        </RootLayout>
      )
    }).not.toThrow()
  })

  it('should handle complex nested children', () => {
    const { getByText, getByRole } = render(
      <RootLayout>
        <header>
          <h1>Header Title</h1>
        </header>
        <main>
          <section>
            <p>Main content paragraph</p>
          </section>
        </main>
        <footer>
          <p>Footer content</p>
        </footer>
      </RootLayout>
    )

    expect(getByRole('banner')).toBeInTheDocument() // header
    expect(getByRole('main')).toBeInTheDocument()
    expect(getByRole('contentinfo')).toBeInTheDocument() // footer
    expect(getByText('Header Title')).toBeInTheDocument()
    expect(getByText('Main content paragraph')).toBeInTheDocument()
    expect(getByText('Footer content')).toBeInTheDocument()
  })
})